### ISSUE TITLE
Crafting takes 2x - 4x required materials.

### ISSUE THREAD

**Issue by CaitlynMainer** [thmsndk/Raft-CraftFromAllStorage#11]
When crafting items (a cup in this example) material use seems to double or quadruple.

https://user-images.githubusercontent.com/1423429/175573465-46d08e84-836d-486d-8266-8b02c60ac1f5.mp4

video of the issue.

**Comment by thmsndk** [comment]
Hmm, that does seem strange, what other mods do you have installed?
What if you reload the game, do you still have the issue then?
I do know that my other mod for Bulk Crafting could mess up the recipe, but a restart would fix it 🤔

**Comment by CaitlynMainer** [comment]
Upon further testing, this appears to be an interaction with More Storages.  I thought I had tested without it, but it seems I was incorrect.  Without that mod installed crafting costs the expected 4 plastic.  With it installed it uses 16.  Not sure if this is an issue on this mod, or that one in this case.

**Comment by thmsndk** [comment]
I did patch MoreStorages when I originally started working on this mod as seen here <https://github.com/thmsndk/Raft-CraftFromAllStorage/blob/master/CraftFromAllStorage/FixMoreStoragesExtensions.cs>

Do you have a reliable reproduce for it?
Is it a specific storage from MoreStorage that causes the issue, or is it enough to just have it installed?

**Comment by CaitlynMainer** [comment]
Just having the mod loaded doesn't cause any issues.  I tested with all of storage options from the MoreStorage mod and they all seemed to cause the issue.  If I have just vanilla storage (with more storage installed, but not used) with plastic crafting costs 4.

Placing a more storage box, and putting plastic in it, but having the Vanilla storage open and crafting costs 8 plastic.  Having the More Storage box open and crafting costs 16 plastic.  Crafting from just the tab menu costs the expected 4 plastic.

Oddly even opening the More Storage box shows that I have 72 more plastic than I actually do. I have 92 plastic, but More Storage says I have 164.  So yeah this is looking to be an issue with More Storage more than with your mod. Apologies.


Reproduction steps if you want to see this in action are straight forward.
Place more storage box (any seem to work) and place plastic into it.
Place vanilla storage box.
Place plastic in both, and note how much you have.
Open the crafting menu with Tab and craft a cup (4 plastic removed as expected)
Open the Vanilla box and craft (8 plastic removed)
Open the More Storage box and craft (Not that More Storage now claims you have more plastic than you should, and 16 plastic is removed when crafting).

**Comment by thmsndk** [comment]
Thanks for the detailed reproduce. The issue is caused by the fact that Raft now also takes resources from the currently open storage. As a result, if you had an open storage, it would take double the amount of resources.

I have not figured out why it would take 16 plastic yet when using More Storages, but I will see if I can figure out what is wrong

**Comment by CaitlynMainer** [comment]
Thanks!
