### ISSUE TITLE
Advanced Biofuel Refiner taking Raw Potatoes when Empty-Handed

### ISSUE THREAD

**Issue by Beefsmeller** [thmsndk/Raft-CraftFromAllStorage#15]
I noticed after putting various refinable resources in the advanced biofuel refiner that once the material is all put in and I'm empty-handed, the prompt to put raw potatoes in is available. For some reason, it only happens with raw potatoes and it actually does take the potatoes from my storage. I have not tested it with the normal biofuel refiner.

**Comment by thmsndk** [comment]
Without the mod will it still ask for putting in potato?

**Comment by Beefsmeller** [comment]
> 

No it won't. It's definitely the mod that's asking for you to put in a potato without it even putting in your inventory.

**Comment by thmsndk** [comment]
Hmm, I would need to test that then, the mod is not explicitly telling anyone to put in potatoes xD it just checks if you have the resources in storage that a mod asks it about.

Perhaps the refiner is asking about potatoes as the first thing 🤔

**Comment by Beefsmeller** [comment]
> Hmm, I would need to test that then, the mod is not explicitly telling anyone to put in potatoes xD it just checks if you have the resources in storage when asked about it :)
> 
> Perhaps the refiner is asking about potatoes as the first thing 🤔

I double checked to make sure Craft From All Storage was the mod doing it. You might be right about the refiner asking about potatoes as the first thing xD. I even switched around the food in chests to see if it was checking the potato chest first. Anyways, I just thought it might be nice to have a way to change that or turn it off cause I keep accidentally putting my potatoes in there. Not a huge deal though.

**Comment by thmsndk** [comment]
I'll take a look at the refiner OnIsRayed code to see how the logic functions and see if there is anything I can do to be smart about it.

**Comment by Beefsmeller** [comment]
> I think this raft code is what triggers it, the potato is the default item for a refiner I assume, and it checks if you have potatoes in your inventory. but this mod when asking the player inventory checks all storages for potatoes as well, so it triggers with a yes and renders the input potato command. ![image](https://user-images.githubusercontent.com/9084377/178315340-26b0b182-fd64-4a55-a6ef-10c86eb4caf1.png)

Oooooooh. Is there a way to fix it?

**Comment by thmsndk** [comment]
Unsure if I can do anything that would make sense without breaking the default behavior of tanks. I guess I could remove the default fuel for the refiners? :P not sure that is a good solution. will have to think about it. 

For now i'm not sure I can do too much about it.

**Comment by thmsndk** [comment]
Would being able to toggle the default item work as a solution? I think that is the best I can come up with
![cfas-toggle-refiner-default-fuel](https://user-images.githubusercontent.com/9084377/178598088-e41c2fc2-d0d5-49b8-a77d-e957cf46b120.gif)

**Comment by Beefsmeller** [comment]
> Would being able to toggle the default item work as a solution? I think that is the best I can come up with ![cfas-toggle-refiner-default-fuel](https://user-images.githubusercontent.com/9084377/178598088-e41c2fc2-d0d5-49b8-a77d-e957cf46b120.gif) [ ![cfas-toggle-refiner-default-fuel](https://user-images.githubusercontent.com/9084377/178598088-e41c2fc2-d0d5-49b8-a77d-e957cf46b120.gif) ](https://user-images.githubusercontent.com/9084377/178598088-e41c2fc2-d0d5-49b8-a77d-e957cf46b120.gif) [ ](https://user-images.githubusercontent.com/9084377/178598088-e41c2fc2-d0d5-49b8-a77d-e957cf46b120.gif)

That would work well if you can't find a way to stop it completely. I sure the community would like that as well xD. Thank you.

**Comment by thmsndk** [comment]
Released in 1.5.0
